### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [s4kibs4mi/ISeeU#1]
Would you mind publishing the APK file here on Github (best on the `releases/` page, see [Creating Releases ](https://help.github.com/articles/creating-releases/) for help)? Quite easy to accomplish – and would give users without Playstore access to your app :)

Thanks in advance!

**Comment by s4kibs4mi** [comment]
Thanks for your valuable comment.
I have added release files. Please checkout release section.

**Comment by IzzySoft** [comment]
Thanks a lot for your fast reaction – really appreciate it!

PS: Added to my [list of video cam apps](https://android.izzysoft.de/applists/category/named/remotedroid_webcams#group_729) :)

**Comment by s4kibs4mi** [comment]
Thank you :)

**Comment by IzzySoft** [comment]
Anytime – that's the least I can do in return :) ~8k hits/day currently for that site, and your app quite on the top of the list – might give a little boost to making it known.
